/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AeoIndexRouteImport } from './routes/aeo.index'
import { Route as AeoAnswerGapsRouteImport } from './routes/aeo.answer-gaps'
import { Route as AeoAnswerOpportunitiesRouteImport } from './routes/aeo.answer-opportunities'
import { Route as AeoFaqCoverageRouteImport } from './routes/aeo.faq-coverage'
import { Route as AeoStructuredAnswersRouteImport } from './routes/aeo.structured-answers'
import { Route as GeoIndexRouteImport } from './routes/geo.index'
import { Route as GeoAiMentionsRouteImport } from './routes/geo.ai-mentions'
import { Route as GeoAiVisibilityRouteImport } from './routes/geo.ai-visibility'
import { Route as GeoContentAuthorityRouteImport } from './routes/geo.content-authority'
import { Route as GeoEntityAuthorityRouteImport } from './routes/geo.entity-authority'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as PagesPageIdRouteImport } from './routes/pages.$pageId'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations.index'
import { Route as RecommendationsRecommendationIdRouteImport } from './routes/recommendations.$recommendationId'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as ResortsIndexRouteImport } from './routes/resorts.index'
import { Route as ResortsResortIdRouteImport } from './routes/resorts.$resortId'
import { Route as SeoIndexRouteImport } from './routes/seo.index'
import { Route as SeoCompetitorsRouteImport } from './routes/seo.competitors'
import { Route as SeoKeywordsRouteImport } from './routes/seo.keywords'
import { Route as SeoOpportunitiesRouteImport } from './routes/seo.opportunities'
import { Route as SeoRankingsRouteImport } from './routes/seo.rankings'
import { Route as SeoTechnicalRouteImport } from './routes/seo.technical'
import { Route as AeoQuestionsIndexRouteImport } from './routes/aeo.questions.index'
import { Route as AeoQuestionsQuestionIdRouteImport } from './routes/aeo.questions.$questionId'
import { Route as GeoAiQueriesIndexRouteImport } from './routes/geo.ai-queries.index'
import { Route as GeoAiQueriesQueryIdRouteImport } from './routes/geo.ai-queries.$queryId'
import { Route as GeoCitationGapIndexRouteImport } from './routes/geo.citation-gap.index'
import { Route as GeoCitationGapGapIdRouteImport } from './routes/geo.citation-gap.$gapId'
import { Route as SeoIssuesIndexRouteImport } from './routes/seo.issues.index'
import { Route as SeoIssuesIssueIdRouteImport } from './routes/seo.issues.$issueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoIndexRoute = AeoIndexRouteImport.update({
  id: '/aeo/',
  path: '/aeo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoAnswerGapsRoute = AeoAnswerGapsRouteImport.update({
  id: '/aeo/answer-gaps',
  path: '/aeo/answer-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoAnswerOpportunitiesRoute = AeoAnswerOpportunitiesRouteImport.update({
  id: '/aeo/answer-opportunities',
  path: '/aeo/answer-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoFaqCoverageRoute = AeoFaqCoverageRouteImport.update({
  id: '/aeo/faq-coverage',
  path: '/aeo/faq-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoStructuredAnswersRoute = AeoStructuredAnswersRouteImport.update({
  id: '/aeo/structured-answers',
  path: '/aeo/structured-answers',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoIndexRoute = GeoIndexRouteImport.update({
  id: '/geo/',
  path: '/geo/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoAiMentionsRoute = GeoAiMentionsRouteImport.update({
  id: '/geo/ai-mentions',
  path: '/geo/ai-mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoAiVisibilityRoute = GeoAiVisibilityRouteImport.update({
  id: '/geo/ai-visibility',
  path: '/geo/ai-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoContentAuthorityRoute = GeoContentAuthorityRouteImport.update({
  id: '/geo/content-authority',
  path: '/geo/content-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoEntityAuthorityRoute = GeoEntityAuthorityRouteImport.update({
  id: '/geo/entity-authority',
  path: '/geo/entity-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/recommendations/',
  path: '/recommendations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRecommendationIdRoute =
  RecommendationsRecommendationIdRouteImport.update({
    id: '/recommendations/$recommendationId',
    path: '/recommendations/$recommendationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortsIndexRoute = ResortsIndexRouteImport.update({
  id: '/resorts/',
  path: '/resorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortsResortIdRoute = ResortsResortIdRouteImport.update({
  id: '/resorts/$resortId',
  path: '/resorts/$resortId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoIndexRoute = SeoIndexRouteImport.update({
  id: '/seo/',
  path: '/seo/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoCompetitorsRoute = SeoCompetitorsRouteImport.update({
  id: '/seo/competitors',
  path: '/seo/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoKeywordsRoute = SeoKeywordsRouteImport.update({
  id: '/seo/keywords',
  path: '/seo/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoOpportunitiesRoute = SeoOpportunitiesRouteImport.update({
  id: '/seo/opportunities',
  path: '/seo/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRankingsRoute = SeoRankingsRouteImport.update({
  id: '/seo/rankings',
  path: '/seo/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoTechnicalRoute = SeoTechnicalRouteImport.update({
  id: '/seo/technical',
  path: '/seo/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoQuestionsIndexRoute = AeoQuestionsIndexRouteImport.update({
  id: '/aeo/questions/',
  path: '/aeo/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoQuestionsQuestionIdRoute = AeoQuestionsQuestionIdRouteImport.update({
  id: '/aeo/questions/$questionId',
  path: '/aeo/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoAiQueriesIndexRoute = GeoAiQueriesIndexRouteImport.update({
  id: '/geo/ai-queries/',
  path: '/geo/ai-queries/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoAiQueriesQueryIdRoute = GeoAiQueriesQueryIdRouteImport.update({
  id: '/geo/ai-queries/$queryId',
  path: '/geo/ai-queries/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoCitationGapIndexRoute = GeoCitationGapIndexRouteImport.update({
  id: '/geo/citation-gap/',
  path: '/geo/citation-gap/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoCitationGapGapIdRoute = GeoCitationGapGapIdRouteImport.update({
  id: '/geo/citation-gap/$gapId',
  path: '/geo/citation-gap/$gapId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoIssuesIndexRoute = SeoIssuesIndexRouteImport.update({
  id: '/seo/issues/',
  path: '/seo/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoIssuesIssueIdRoute = SeoIssuesIssueIdRouteImport.update({
  id: '/seo/issues/$issueId',
  path: '/seo/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRoute
  '/aeo/answer-gaps': typeof AeoAnswerGapsRoute
  '/aeo/answer-opportunities': typeof AeoAnswerOpportunitiesRoute
  '/aeo/faq-coverage': typeof AeoFaqCoverageRoute
  '/aeo/structured-answers': typeof AeoStructuredAnswersRoute
  '/geo/ai-mentions': typeof GeoAiMentionsRoute
  '/geo/ai-visibility': typeof GeoAiVisibilityRoute
  '/geo/content-authority': typeof GeoContentAuthorityRoute
  '/geo/entity-authority': typeof GeoEntityAuthorityRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/resorts/$resortId': typeof ResortsResortIdRoute
  '/seo/competitors': typeof SeoCompetitorsRoute
  '/seo/keywords': typeof SeoKeywordsRoute
  '/seo/opportunities': typeof SeoOpportunitiesRoute
  '/seo/rankings': typeof SeoRankingsRoute
  '/seo/technical': typeof SeoTechnicalRoute
  '/aeo/': typeof AeoIndexRoute
  '/geo/': typeof GeoIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/resorts/': typeof ResortsIndexRoute
  '/seo/': typeof SeoIndexRoute
  '/aeo/questions/$questionId': typeof AeoQuestionsQuestionIdRoute
  '/geo/ai-queries/$queryId': typeof GeoAiQueriesQueryIdRoute
  '/geo/citation-gap/$gapId': typeof GeoCitationGapGapIdRoute
  '/seo/issues/$issueId': typeof SeoIssuesIssueIdRoute
  '/aeo/questions/': typeof AeoQuestionsIndexRoute
  '/geo/ai-queries/': typeof GeoAiQueriesIndexRoute
  '/geo/citation-gap/': typeof GeoCitationGapIndexRoute
  '/seo/issues/': typeof SeoIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRoute
  '/aeo/answer-gaps': typeof AeoAnswerGapsRoute
  '/aeo/answer-opportunities': typeof AeoAnswerOpportunitiesRoute
  '/aeo/faq-coverage': typeof AeoFaqCoverageRoute
  '/aeo/structured-answers': typeof AeoStructuredAnswersRoute
  '/geo/ai-mentions': typeof GeoAiMentionsRoute
  '/geo/ai-visibility': typeof GeoAiVisibilityRoute
  '/geo/content-authority': typeof GeoContentAuthorityRoute
  '/geo/entity-authority': typeof GeoEntityAuthorityRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/resorts/$resortId': typeof ResortsResortIdRoute
  '/seo/competitors': typeof SeoCompetitorsRoute
  '/seo/keywords': typeof SeoKeywordsRoute
  '/seo/opportunities': typeof SeoOpportunitiesRoute
  '/seo/rankings': typeof SeoRankingsRoute
  '/seo/technical': typeof SeoTechnicalRoute
  '/aeo': typeof AeoIndexRoute
  '/geo': typeof GeoIndexRoute
  '/pages': typeof PagesIndexRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/resorts': typeof ResortsIndexRoute
  '/seo': typeof SeoIndexRoute
  '/aeo/questions/$questionId': typeof AeoQuestionsQuestionIdRoute
  '/geo/ai-queries/$queryId': typeof GeoAiQueriesQueryIdRoute
  '/geo/citation-gap/$gapId': typeof GeoCitationGapGapIdRoute
  '/seo/issues/$issueId': typeof SeoIssuesIssueIdRoute
  '/aeo/questions': typeof AeoQuestionsIndexRoute
  '/geo/ai-queries': typeof GeoAiQueriesIndexRoute
  '/geo/citation-gap': typeof GeoCitationGapIndexRoute
  '/seo/issues': typeof SeoIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRoute
  '/aeo/answer-gaps': typeof AeoAnswerGapsRoute
  '/aeo/answer-opportunities': typeof AeoAnswerOpportunitiesRoute
  '/aeo/faq-coverage': typeof AeoFaqCoverageRoute
  '/aeo/structured-answers': typeof AeoStructuredAnswersRoute
  '/geo/ai-mentions': typeof GeoAiMentionsRoute
  '/geo/ai-visibility': typeof GeoAiVisibilityRoute
  '/geo/content-authority': typeof GeoContentAuthorityRoute
  '/geo/entity-authority': typeof GeoEntityAuthorityRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/resorts/$resortId': typeof ResortsResortIdRoute
  '/seo/competitors': typeof SeoCompetitorsRoute
  '/seo/keywords': typeof SeoKeywordsRoute
  '/seo/opportunities': typeof SeoOpportunitiesRoute
  '/seo/rankings': typeof SeoRankingsRoute
  '/seo/technical': typeof SeoTechnicalRoute
  '/aeo/': typeof AeoIndexRoute
  '/geo/': typeof GeoIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/resorts/': typeof ResortsIndexRoute
  '/seo/': typeof SeoIndexRoute
  '/aeo/questions/$questionId': typeof AeoQuestionsQuestionIdRoute
  '/geo/ai-queries/$queryId': typeof GeoAiQueriesQueryIdRoute
  '/geo/citation-gap/$gapId': typeof GeoCitationGapGapIdRoute
  '/seo/issues/$issueId': typeof SeoIssuesIssueIdRoute
  '/aeo/questions/': typeof AeoQuestionsIndexRoute
  '/geo/ai-queries/': typeof GeoAiQueriesIndexRoute
  '/geo/citation-gap/': typeof GeoCitationGapIndexRoute
  '/seo/issues/': typeof SeoIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/settings'
    | '/aeo/answer-gaps'
    | '/aeo/answer-opportunities'
    | '/aeo/faq-coverage'
    | '/aeo/structured-answers'
    | '/geo/ai-mentions'
    | '/geo/ai-visibility'
    | '/geo/content-authority'
    | '/geo/entity-authority'
    | '/pages/$pageId'
    | '/recommendations/$recommendationId'
    | '/reports/$reportId'
    | '/resorts/$resortId'
    | '/seo/competitors'
    | '/seo/keywords'
    | '/seo/opportunities'
    | '/seo/rankings'
    | '/seo/technical'
    | '/aeo/'
    | '/geo/'
    | '/pages/'
    | '/recommendations/'
    | '/reports/'
    | '/resorts/'
    | '/seo/'
    | '/aeo/questions/$questionId'
    | '/geo/ai-queries/$queryId'
    | '/geo/citation-gap/$gapId'
    | '/seo/issues/$issueId'
    | '/aeo/questions/'
    | '/geo/ai-queries/'
    | '/geo/citation-gap/'
    | '/seo/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/settings'
    | '/aeo/answer-gaps'
    | '/aeo/answer-opportunities'
    | '/aeo/faq-coverage'
    | '/aeo/structured-answers'
    | '/geo/ai-mentions'
    | '/geo/ai-visibility'
    | '/geo/content-authority'
    | '/geo/entity-authority'
    | '/pages/$pageId'
    | '/recommendations/$recommendationId'
    | '/reports/$reportId'
    | '/resorts/$resortId'
    | '/seo/competitors'
    | '/seo/keywords'
    | '/seo/opportunities'
    | '/seo/rankings'
    | '/seo/technical'
    | '/aeo'
    | '/geo'
    | '/pages'
    | '/recommendations'
    | '/reports'
    | '/resorts'
    | '/seo'
    | '/aeo/questions/$questionId'
    | '/geo/ai-queries/$queryId'
    | '/geo/citation-gap/$gapId'
    | '/seo/issues/$issueId'
    | '/aeo/questions'
    | '/geo/ai-queries'
    | '/geo/citation-gap'
    | '/seo/issues'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/settings'
    | '/aeo/answer-gaps'
    | '/aeo/answer-opportunities'
    | '/aeo/faq-coverage'
    | '/aeo/structured-answers'
    | '/geo/ai-mentions'
    | '/geo/ai-visibility'
    | '/geo/content-authority'
    | '/geo/entity-authority'
    | '/pages/$pageId'
    | '/recommendations/$recommendationId'
    | '/reports/$reportId'
    | '/resorts/$resortId'
    | '/seo/competitors'
    | '/seo/keywords'
    | '/seo/opportunities'
    | '/seo/rankings'
    | '/seo/technical'
    | '/aeo/'
    | '/geo/'
    | '/pages/'
    | '/recommendations/'
    | '/reports/'
    | '/resorts/'
    | '/seo/'
    | '/aeo/questions/$questionId'
    | '/geo/ai-queries/$queryId'
    | '/geo/citation-gap/$gapId'
    | '/seo/issues/$issueId'
    | '/aeo/questions/'
    | '/geo/ai-queries/'
    | '/geo/citation-gap/'
    | '/seo/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  SettingsRoute: typeof SettingsRoute
  AeoAnswerGapsRoute: typeof AeoAnswerGapsRoute
  AeoAnswerOpportunitiesRoute: typeof AeoAnswerOpportunitiesRoute
  AeoFaqCoverageRoute: typeof AeoFaqCoverageRoute
  AeoStructuredAnswersRoute: typeof AeoStructuredAnswersRoute
  GeoAiMentionsRoute: typeof GeoAiMentionsRoute
  GeoAiVisibilityRoute: typeof GeoAiVisibilityRoute
  GeoContentAuthorityRoute: typeof GeoContentAuthorityRoute
  GeoEntityAuthorityRoute: typeof GeoEntityAuthorityRoute
  PagesPageIdRoute: typeof PagesPageIdRoute
  RecommendationsRecommendationIdRoute: typeof RecommendationsRecommendationIdRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  ResortsResortIdRoute: typeof ResortsResortIdRoute
  SeoCompetitorsRoute: typeof SeoCompetitorsRoute
  SeoKeywordsRoute: typeof SeoKeywordsRoute
  SeoOpportunitiesRoute: typeof SeoOpportunitiesRoute
  SeoRankingsRoute: typeof SeoRankingsRoute
  SeoTechnicalRoute: typeof SeoTechnicalRoute
  AeoIndexRoute: typeof AeoIndexRoute
  GeoIndexRoute: typeof GeoIndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ResortsIndexRoute: typeof ResortsIndexRoute
  SeoIndexRoute: typeof SeoIndexRoute
  AeoQuestionsQuestionIdRoute: typeof AeoQuestionsQuestionIdRoute
  GeoAiQueriesQueryIdRoute: typeof GeoAiQueriesQueryIdRoute
  GeoCitationGapGapIdRoute: typeof GeoCitationGapGapIdRoute
  SeoIssuesIssueIdRoute: typeof SeoIssuesIssueIdRoute
  AeoQuestionsIndexRoute: typeof AeoQuestionsIndexRoute
  GeoAiQueriesIndexRoute: typeof GeoAiQueriesIndexRoute
  GeoCitationGapIndexRoute: typeof GeoCitationGapIndexRoute
  SeoIssuesIndexRoute: typeof SeoIssuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo/': {
      id: '/aeo/'
      path: '/aeo'
      fullPath: '/aeo/'
      preLoaderRoute: typeof AeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo/answer-gaps': {
      id: '/aeo/answer-gaps'
      path: '/aeo/answer-gaps'
      fullPath: '/aeo/answer-gaps'
      preLoaderRoute: typeof AeoAnswerGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo/answer-opportunities': {
      id: '/aeo/answer-opportunities'
      path: '/aeo/answer-opportunities'
      fullPath: '/aeo/answer-opportunities'
      preLoaderRoute: typeof AeoAnswerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo/faq-coverage': {
      id: '/aeo/faq-coverage'
      path: '/aeo/faq-coverage'
      fullPath: '/aeo/faq-coverage'
      preLoaderRoute: typeof AeoFaqCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo/structured-answers': {
      id: '/aeo/structured-answers'
      path: '/aeo/structured-answers'
      fullPath: '/aeo/structured-answers'
      preLoaderRoute: typeof AeoStructuredAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/': {
      id: '/geo/'
      path: '/geo'
      fullPath: '/geo/'
      preLoaderRoute: typeof GeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/ai-mentions': {
      id: '/geo/ai-mentions'
      path: '/geo/ai-mentions'
      fullPath: '/geo/ai-mentions'
      preLoaderRoute: typeof GeoAiMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/ai-visibility': {
      id: '/geo/ai-visibility'
      path: '/geo/ai-visibility'
      fullPath: '/geo/ai-visibility'
      preLoaderRoute: typeof GeoAiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/content-authority': {
      id: '/geo/content-authority'
      path: '/geo/content-authority'
      fullPath: '/geo/content-authority'
      preLoaderRoute: typeof GeoContentAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/entity-authority': {
      id: '/geo/entity-authority'
      path: '/geo/entity-authority'
      fullPath: '/geo/entity-authority'
      preLoaderRoute: typeof GeoEntityAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/recommendations'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/$recommendationId': {
      id: '/recommendations/$recommendationId'
      path: '/recommendations/$recommendationId'
      fullPath: '/recommendations/$recommendationId'
      preLoaderRoute: typeof RecommendationsRecommendationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resorts/': {
      id: '/resorts/'
      path: '/resorts'
      fullPath: '/resorts/'
      preLoaderRoute: typeof ResortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resorts/$resortId': {
      id: '/resorts/$resortId'
      path: '/resorts/$resortId'
      fullPath: '/resorts/$resortId'
      preLoaderRoute: typeof ResortsResortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/': {
      id: '/seo/'
      path: '/seo'
      fullPath: '/seo/'
      preLoaderRoute: typeof SeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/competitors': {
      id: '/seo/competitors'
      path: '/seo/competitors'
      fullPath: '/seo/competitors'
      preLoaderRoute: typeof SeoCompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/keywords': {
      id: '/seo/keywords'
      path: '/seo/keywords'
      fullPath: '/seo/keywords'
      preLoaderRoute: typeof SeoKeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/opportunities': {
      id: '/seo/opportunities'
      path: '/seo/opportunities'
      fullPath: '/seo/opportunities'
      preLoaderRoute: typeof SeoOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/rankings': {
      id: '/seo/rankings'
      path: '/seo/rankings'
      fullPath: '/seo/rankings'
      preLoaderRoute: typeof SeoRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/technical': {
      id: '/seo/technical'
      path: '/seo/technical'
      fullPath: '/seo/technical'
      preLoaderRoute: typeof SeoTechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo/questions/': {
      id: '/aeo/questions/'
      path: '/aeo/questions'
      fullPath: '/aeo/questions/'
      preLoaderRoute: typeof AeoQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo/questions/$questionId': {
      id: '/aeo/questions/$questionId'
      path: '/aeo/questions/$questionId'
      fullPath: '/aeo/questions/$questionId'
      preLoaderRoute: typeof AeoQuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/ai-queries/': {
      id: '/geo/ai-queries/'
      path: '/geo/ai-queries'
      fullPath: '/geo/ai-queries/'
      preLoaderRoute: typeof GeoAiQueriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/ai-queries/$queryId': {
      id: '/geo/ai-queries/$queryId'
      path: '/geo/ai-queries/$queryId'
      fullPath: '/geo/ai-queries/$queryId'
      preLoaderRoute: typeof GeoAiQueriesQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/citation-gap/': {
      id: '/geo/citation-gap/'
      path: '/geo/citation-gap'
      fullPath: '/geo/citation-gap/'
      preLoaderRoute: typeof GeoCitationGapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo/citation-gap/$gapId': {
      id: '/geo/citation-gap/$gapId'
      path: '/geo/citation-gap/$gapId'
      fullPath: '/geo/citation-gap/$gapId'
      preLoaderRoute: typeof GeoCitationGapGapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/issues/': {
      id: '/seo/issues/'
      path: '/seo/issues'
      fullPath: '/seo/issues/'
      preLoaderRoute: typeof SeoIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo/issues/$issueId': {
      id: '/seo/issues/$issueId'
      path: '/seo/issues/$issueId'
      fullPath: '/seo/issues/$issueId'
      preLoaderRoute: typeof SeoIssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  SettingsRoute: SettingsRoute,
  AeoAnswerGapsRoute: AeoAnswerGapsRoute,
  AeoAnswerOpportunitiesRoute: AeoAnswerOpportunitiesRoute,
  AeoFaqCoverageRoute: AeoFaqCoverageRoute,
  AeoStructuredAnswersRoute: AeoStructuredAnswersRoute,
  GeoAiMentionsRoute: GeoAiMentionsRoute,
  GeoAiVisibilityRoute: GeoAiVisibilityRoute,
  GeoContentAuthorityRoute: GeoContentAuthorityRoute,
  GeoEntityAuthorityRoute: GeoEntityAuthorityRoute,
  PagesPageIdRoute: PagesPageIdRoute,
  RecommendationsRecommendationIdRoute: RecommendationsRecommendationIdRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  ResortsResortIdRoute: ResortsResortIdRoute,
  SeoCompetitorsRoute: SeoCompetitorsRoute,
  SeoKeywordsRoute: SeoKeywordsRoute,
  SeoOpportunitiesRoute: SeoOpportunitiesRoute,
  SeoRankingsRoute: SeoRankingsRoute,
  SeoTechnicalRoute: SeoTechnicalRoute,
  AeoIndexRoute: AeoIndexRoute,
  GeoIndexRoute: GeoIndexRoute,
  PagesIndexRoute: PagesIndexRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ResortsIndexRoute: ResortsIndexRoute,
  SeoIndexRoute: SeoIndexRoute,
  AeoQuestionsQuestionIdRoute: AeoQuestionsQuestionIdRoute,
  GeoAiQueriesQueryIdRoute: GeoAiQueriesQueryIdRoute,
  GeoCitationGapGapIdRoute: GeoCitationGapGapIdRoute,
  SeoIssuesIssueIdRoute: SeoIssuesIssueIdRoute,
  AeoQuestionsIndexRoute: AeoQuestionsIndexRoute,
  GeoAiQueriesIndexRoute: GeoAiQueriesIndexRoute,
  GeoCitationGapIndexRoute: GeoCitationGapIndexRoute,
  SeoIssuesIndexRoute: SeoIssuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
